services:
  newt:
    image: fosrl/newt:latest
    container_name: newt
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.joseluna.dev
      - NEWT_ID=l9a1ol963latjee
      - NEWT_SECRET=gqh0azjzml1sqw9t2lzqrvimw5sgaflvw27w9dn2dtq18bji
      - DOCKER_SOCKET=unix:///var/run/docker.sock
    networks:
      - newt

networks:
  newt:
   name: newt
