http:
  routers:
    netdata:
      rule: "Host(`netdata.joseluna.dev`)"   # cambia dominio
      entryPoints:
        - https
      tls:
        certResolver: cloudflare 
      service: netdata

  services:
    netdata:
      loadBalancer:
        servers:
          - url: "http://10.0.0.6:19999"
