services:
  syncyomi:
    image: ghcr.io/syncyomi/syncyomi:latest
    container_name: syncyomi
    restart: unless-stopped
    environment:
      TZ: America/Santiago
    volumes:
      - ./data/syncyomi/config:/config
    networks:
      - proxy

networks:
  proxy:
    external: true
