services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.joseluna.dev
      - NEWT_ID=kpkh1q1hdgrrqfc
      - NEWT_SECRET=jzb7nbehonjpwqp2oglaj10ay92pnlj5em1cryyv4s0zc55f
    networks:
      - newt

networks:
  newt:
   name: newt
