services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: litellm
    dns:
      - 10.0.0.4
      - 10.0.0.16
    environment:
      DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
      STORE_MODEL_IN_DB: "True"
      TZ: "America/Santiago"
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "python3 -c \"import urllib.request; urllib.request.urlopen('http://localhost:4000/health/liveliness')\" || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy
      - litellm

  db:
    image: postgres:16-alpine
    restart: always
    container_name: litellm_db
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data-litellm:/var/lib/postgresql/data
    networks:
      - litellm
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d litellm -U llmproxy" ]
      interval: 2s
      timeout: 5s
      retries: 10

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: litellm-prometheus
    networks:
      - litellm
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    restart: always

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    restart: unless-stopped
    volumes:
      - /config/openwebui/data:/app/backend/data
    environment:
      - TZ=America/Santiago
      - WEBUI_URL=${WEBUI_URL}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME}
      - OPENID_PROVIDER_URL=${OPENID_PROVIDER_URL}
      - OAUTH_SCOPES=${OAUTH_SCOPES}
      - ENABLE_OAUTH_SIGNUP=${ENABLE_OAUTH_SIGNUP}
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=${OAUTH_MERGE_ACCOUNTS_BY_EMAIL}
    networks:
      - proxy
      - litellm
    dns:
      - 10.0.0.4
      - 10.0.0.16

networks:
  proxy:
    external: true
  litellm:
    name: litellm
